apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging-triggers
  namespace: pipelines
data:
  zap-logger-config: |
    {
      "level": "debug",
      "development": true,
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "timestamp",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "message",
        "stacktraceKey": "stacktrace",
        "levelEncoder": "lowercase"
      }
    }
