apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-mock-listener
  annotations:
    triggers.tekton.dev/debug: "true"
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-mock-trigger
      bindings:
        - ref: github-mock-binding
      template:
        ref: github-mock-template
