apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-mock-listener
spec:
  serviceAccountName: tekton-trigger-sa
  triggers:
    - name: github-mock-trigger
      interceptors:
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.message != ''"
            - name: "overlays"
              value:
                - key: "timestamp"
                  expression: "string(parseTime('2006-01-02T15:04:05.999Z07:00', timestamp()))"
      bindings:
        - ref: github-mock-binding
      template:
        ref: github-mock-template
