apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: simple-print
spec:
  params:
    - name: message
      type: string
    - name: repo-name
      type: string
  steps:
    - name: print-message
      image: alpine
      script: |
        #!/bin/sh
        echo "=== Event Details ==="
        echo "Received message: $(params.message)"
        echo "Repository name: $(params.repo-name)"
        echo "Current time: $(date)"
        echo "===================="
