apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-mock-template
spec:
  params:
    - name: message
      description: "Message from the incoming request"
    - name: repository
      description: "Repository name from the request"
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: simple-pipeline-run-
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: simple-pipeline
        params:
          - name: message
            value: $(tt.params.message)
          - name: repo-name
            value: $(tt.params.repository)
